INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, USERNAME, PASSWORD, SALT, IS_ACTIVE)
  VALUES (1, 'Bilal', 'CHAMI', '1995-06-08', 'test@test.com', 'bilal', 'bilal', 'E1F53135E559C253', 1);

INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, USERNAME, PASSWORD, SALT, IS_ACTIVE)
  VALUES (2, 'Elie', 'DAHER', '1995-05-03', 'elie@test.com', 'elie', 'elie', '84B03D034B409D4E', 1);

INSERT INTO ROLE (ID, NAME, AUTHORITY, IS_ACTIVE)
  VALUES (1, 'ADMIN', 'ROLE_ADMIN', 1);

INSERT INTO ROLE (ID, NAME, AUTHORITY, IS_ACTIVE)
  VALUES (2, 'Client', 'ROLE_CLIENT', 1);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
  VALUES (1, 1);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
  VALUES (2, 2);